#debug: true
spring:
  profiles:
    active: nonprod
server:
  port: 8082

---
spring:
  kafka:
    topic:
      retry: library-events.RETRY
      dlt: library-events.DLT
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
    producer:
      bootstrap-servers:
        - localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: local

---
spring:
  kafka:
    topic:
      retry: library-events.RETRY
      dlt: library-events.DLT
    consumer:
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: library-events-listener-group
      ssl:
        trust-store-location: file:/D:/projects/2022-23/dilip/ssl/client.truststore.jks
        trust-store-password: password
        key-store-location: file:/D:/projects/2022-23/dilip/ssl/client.keystore.jks
        key-store-password: password
      properties:
        security:
          protocol: SSL
        ssl.endpoint.identification.algorithm:
    producer:
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true
  config:
    activate:
      on-profile: nonprod